export const defaultDateFormat = 'YYYYMMDDHHmm'
export const longDateFormat = 'YYYY/MM/DD HH:mm:ss'
export const defaultHourFormat = 'HHmm'
export const dateFormattedFormat = 'DD.MM.YYYY HH:mm'
export const shortDateFormat = 'YYYYMMDD'
export const shortHourFormat = 'HHmm'
